# Generated by Django 2.0.7 on 2018-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='review_counter',
            field=models.IntegerField(default=0),
        ),
    ]
